// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CharacterOrAbilityCreatorModal: typeof import('./src/components/CharacterOrAbilityCreatorModal.vue')['default']
    CharacterOrAbilityRow: typeof import('./src/components/CharacterOrAbilityRow.vue')['default']
    CharacterOrAbilityShowModal: typeof import('./src/components/CharacterOrAbilityShowModal/CharacterOrAbilityShowModal.vue')['default']
    CustomLayout: typeof import('./src/components/CustomLayout.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    HidableIlustration: typeof import('./src/components/HidableIlustration.vue')['default']
    HidableText: typeof import('./src/components/HidableText.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    IlustrationImg: typeof import('./src/components/IlustrationImg.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    LocaleSelector: typeof import('./src/components/LocaleSelector.vue')['default']
    PlayerCard: typeof import('./src/components/PlayerCard.vue')['default']
    RoleCarrousel: typeof import('./src/components/distribute-roles/RoleCarrousel.vue')['default']
    RoleCarrouselItem: typeof import('./src/components/distribute-roles/RoleCarrouselItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList.vue')['default']
  }
}
